import React from 'react';
import { connect } from 'react-redux';
import * as actions from '../redux/actions';
import { Icon } from 'react-native-elements';
import {
  ScrollView,
  StyleSheet,
  Text,
  Button,
  View,
  Image,
} from 'react-native';
import { Bubbles } from 'react-native-loader';
import { withTheme } from 'react-native-elements';

class LinksScreen extends React.Component {
  onPress = () => {
    this.props.navigation.navigate('Main');
  };
  componentDidMount() {
    const name = this.props.navigation.state.params.name;
    this.props.dispatch(actions.getPhotos(name));
  }
  render() {
    const { photos, usersLoading } = this.props;
    if (!photos || usersLoading) {
      return (
        <View style={styles.loader}>
          <Bubbles size={20} color={`black`} />
        </View>
      );
    }

    return (
      <ScrollView style={styles.container} stickyHeaderIndices={[0]}>
        <Button style={styles.button} onPress={this.onPress} title="back" />
        <View style={styles.wrapper}>
          <Image
            style={styles.profile_image}
            source={{ uri: photos[0].user.profile_image.large }}
          />
          <Text style={styles.title}>{photos[0].user.bio}</Text>
        </View>
        {photos.map((item, i) => {
          return (
            <View style={styles.photos} key={i}>
              <Image
                style={styles.photos__item}
                source={{ uri: item.urls.regular }}
              />
              <View style={styles.footer}>
                <Icon name="md-heart" type="ionicon" color="white" />
                <Text style={styles.info}>{item.likes}</Text>
              </View>
            </View>
          );
        })}
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 25,
    backgroundColor: 'red',
  },
  info: {
    color: `white`,
    fontSize: 20,
    marginLeft: 10,
  },
  footer: {
    flexDirection: `row`,
    backgroundColor: `rgba(0,0,0,0.7)`,
    paddingLeft: 50,
    paddingTop: 30,
    height: 70,
  },
  wrapper: {
    paddingTop: 40,
    flexDirection: `row`,
    paddingLeft: 40,
    borderBottomColor: `white`,
    paddingBottom: 20,
    borderBottomWidth: 1,
    marginBottom: 30,
  },
  photos: {
    height: 350,
    width: `100%`,
    marginBottom: 40,
  },
  photos__item: {
    borderColor: `white`,
    borderWidth: 2,
    width: `100%`,
    height: 280,
  },
  profile_image: {
    width: 120,
    height: 120,
    borderRadius: 80,
  },
  title: {
    color: `white`,
    fontSize: 17,
    width: 0,
    flexGrow: 1,
    flex: 1,
    marginLeft: 10,
  },

  loader: {
    width: `100%`,
    height: `100%`,
    backgroundColor: `red`,
    flexDirection: `row`,
    alignItems: `center`,
    justifyContent: `center`,
  },
});
const mapStateToProps = state => {
  const { photos, usersLoading } = state;

  return {
    photos,
    usersLoading,
  };
};
export default connect(mapStateToProps)(LinksScreen);
// Array[
//   Object {
//   "alt_description": null,
//     "categories": Array[],
//       "color": "#FDCF13",
//         "created_at": "2019-03-07T11:23:24-05:00",
//           "current_user_collections": Array[],
//             "description": null,
//               "height": 3995,
//                 "id": "MTtYAZR8A08",
//                   "liked_by_user": false,
//                     "likes": 0,
//                       "links": Object {
//     "download": "https://unsplash.com/photos/MTtYAZR8A08/download",
//       "download_location": "https://api.unsplash.com/photos/MTtYAZR8A08/download",
//         "html": "https://unsplash.com/photos/MTtYAZR8A08",
//           "self": "https://api.unsplash.com/photos/MTtYAZR8A08",
//     },
//   "sponsored": false,
//     "sponsored_by": null,
//       "sponsored_impressions_id": null,
//         "updated_at": "2019-03-08T10:02:36-05:00",
//           "urls": Object {
//     "full": "https://images.unsplash.com/photo-1551973931-e416eb60135a?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//       "raw": "https://images.unsplash.com/photo-1551973931-e416eb60135a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//         "regular": "https://images.unsplash.com/photo-1551973931-e416eb60135a?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//           "small": "https://images.unsplash.com/photo-1551973931-e416eb60135a?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//             "thumb": "https://images.unsplash.com/photo-1551973931-e416eb60135a?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//     },
//   "user": Object {
//     "accepted_tos": true,
//       "bio": "My goal is to dream big, be awesome, change lives, and maybe get some cool shots I can share with you along the way.",
//         "first_name": "Clayton",
//           "id": "XWgtCn3n3KU",
//             "instagram_username": "clayton_cardinalli",
//               "last_name": "Cardinalli",
//                 "links": Object {
//       "followers": "https://api.unsplash.com/users/clayton_cardinalli/followers",
//         "following": "https://api.unsplash.com/users/clayton_cardinalli/following",
//           "html": "https://unsplash.com/@clayton_cardinalli",
//             "likes": "https://api.unsplash.com/users/clayton_cardinalli/likes",
//               "photos": "https://api.unsplash.com/users/clayton_cardinalli/photos",
//                 "portfolio": "https://api.unsplash.com/users/clayton_cardinalli/portfolio",
//                   "self": "https://api.unsplash.com/users/clayton_cardinalli",
//       },
//     "location": "Cape Town",
//       "name": "Clayton Cardinalli",
//         "portfolio_url": "https://www.havedronecanfly.com/",
//           "profile_image": Object {
//       "large": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
//         "medium": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64",
//           "small": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32",
//       },
//     "total_collections": 3,
//       "total_likes": 50,
//         "total_photos": 51,
//           "twitter_username": "clayton_card",
//             "updated_at": "2019-03-06T09:10:12-05:00",
//               "username": "clayton_cardinalli",
//     },
//   "width": 5992,
//   },
// Object {
//   "alt_description": null,
//     "categories": Array[],
//       "color": "#0F0B10",
//         "created_at": "2019-03-07T11:23:24-05:00",
//           "current_user_collections": Array[],
//             "description": null,
//               "height": 6000,
//                 "id": "W2JGFmXHlIM",
//                   "liked_by_user": false,
//                     "likes": 8,
//                       "links": Object {
//     "download": "https://unsplash.com/photos/W2JGFmXHlIM/download",
//       "download_location": "https://api.unsplash.com/photos/W2JGFmXHlIM/download",
//         "html": "https://unsplash.com/photos/W2JGFmXHlIM",
//           "self": "https://api.unsplash.com/photos/W2JGFmXHlIM",
//     },
//   "sponsored": false,
//     "sponsored_by": null,
//       "sponsored_impressions_id": null,
//         "updated_at": "2019-03-08T09:21:51-05:00",
//           "urls": Object {
//     "full": "https://images.unsplash.com/photo-1551973931-6540173322a5?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//       "raw": "https://images.unsplash.com/photo-1551973931-6540173322a5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//         "regular": "https://images.unsplash.com/photo-1551973931-6540173322a5?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//           "small": "https://images.unsplash.com/photo-1551973931-6540173322a5?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//             "thumb": "https://images.unsplash.com/photo-1551973931-6540173322a5?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//     },
//   "user": Object {
//     "accepted_tos": true,
//       "bio": "My goal is to dream big, be awesome, change lives, and maybe get some cool shots I can share with you along the way.",
//         "first_name": "Clayton",
//           "id": "XWgtCn3n3KU",
//             "instagram_username": "clayton_cardinalli",
//               "last_name": "Cardinalli",
//                 "links": Object {
//       "followers": "https://api.unsplash.com/users/clayton_cardinalli/followers",
//         "following": "https://api.unsplash.com/users/clayton_cardinalli/following",
//           "html": "https://unsplash.com/@clayton_cardinalli",
//             "likes": "https://api.unsplash.com/users/clayton_cardinalli/likes",
//               "photos": "https://api.unsplash.com/users/clayton_cardinalli/photos",
//                 "portfolio": "https://api.unsplash.com/users/clayton_cardinalli/portfolio",
//                   "self": "https://api.unsplash.com/users/clayton_cardinalli",
//       },
//     "location": "Cape Town",
//       "name": "Clayton Cardinalli",
//         "portfolio_url": "https://www.havedronecanfly.com/",
//           "profile_image": Object {
//       "large": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
//         "medium": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64",
//           "small": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32",
//       },
//     "total_collections": 3,
//       "total_likes": 50,
//         "total_photos": 51,
//           "twitter_username": "clayton_card",
//             "updated_at": "2019-03-06T09:10:12-05:00",
//               "username": "clayton_cardinalli",
//     },
//   "width": 4000,
//   },
// Object {
//   "alt_description": null,
//     "categories": Array[],
//       "color": "#1D2329",
//         "created_at": "2019-03-07T11:23:24-05:00",
//           "current_user_collections": Array[],
//             "description": null,
//               "height": 6000,
//                 "id": "YNqtAswUlDI",
//                   "liked_by_user": false,
//                     "likes": 1,
//                       "links": Object {
//     "download": "https://unsplash.com/photos/YNqtAswUlDI/download",
//       "download_location": "https://api.unsplash.com/photos/YNqtAswUlDI/download",
//         "html": "https://unsplash.com/photos/YNqtAswUlDI",
//           "self": "https://api.unsplash.com/photos/YNqtAswUlDI",
//     },
//   "sponsored": false,
//     "sponsored_by": null,
//       "sponsored_impressions_id": null,
//         "updated_at": "2019-03-08T09:54:30-05:00",
//           "urls": Object {
//     "full": "https://images.unsplash.com/photo-1551973931-66bacf500002?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//       "raw": "https://images.unsplash.com/photo-1551973931-66bacf500002?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//         "regular": "https://images.unsplash.com/photo-1551973931-66bacf500002?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//           "small": "https://images.unsplash.com/photo-1551973931-66bacf500002?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//             "thumb": "https://images.unsplash.com/photo-1551973931-66bacf500002?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//     },
//   "user": Object {
//     "accepted_tos": true,
//       "bio": "My goal is to dream big, be awesome, change lives, and maybe get some cool shots I can share with you along the way.",
//         "first_name": "Clayton",
//           "id": "XWgtCn3n3KU",
//             "instagram_username": "clayton_cardinalli",
//               "last_name": "Cardinalli",
//                 "links": Object {
//       "followers": "https://api.unsplash.com/users/clayton_cardinalli/followers",
//         "following": "https://api.unsplash.com/users/clayton_cardinalli/following",
//           "html": "https://unsplash.com/@clayton_cardinalli",
//             "likes": "https://api.unsplash.com/users/clayton_cardinalli/likes",
//               "photos": "https://api.unsplash.com/users/clayton_cardinalli/photos",
//                 "portfolio": "https://api.unsplash.com/users/clayton_cardinalli/portfolio",
//                   "self": "https://api.unsplash.com/users/clayton_cardinalli",
//       },
//     "location": "Cape Town",
//       "name": "Clayton Cardinalli",
//         "portfolio_url": "https://www.havedronecanfly.com/",
//           "profile_image": Object {
//       "large": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
//         "medium": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64",
//           "small": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32",
//       },
//     "total_collections": 3,
//       "total_likes": 50,
//         "total_photos": 51,
//           "twitter_username": "clayton_card",
//             "updated_at": "2019-03-06T09:10:12-05:00",
//               "username": "clayton_cardinalli",
//     },
//   "width": 4000,
//   },
// Object {
//   "alt_description": null,
//     "categories": Array[],
//       "color": "#003615",
//         "created_at": "2019-03-07T11:23:24-05:00",
//           "current_user_collections": Array[],
//             "description": null,
//               "height": 4000,
//                 "id": "g4GfZjRRygg",
//                   "liked_by_user": false,
//                     "likes": 27,
//                       "links": Object {
//     "download": "https://unsplash.com/photos/g4GfZjRRygg/download",
//       "download_location": "https://api.unsplash.com/photos/g4GfZjRRygg/download",
//         "html": "https://unsplash.com/photos/g4GfZjRRygg",
//           "self": "https://api.unsplash.com/photos/g4GfZjRRygg",
//     },
//   "sponsored": false,
//     "sponsored_by": null,
//       "sponsored_impressions_id": null,
//         "updated_at": "2019-03-08T11:34:57-05:00",
//           "urls": Object {
//     "full": "https://images.unsplash.com/photo-1551973932-8131a944f98e?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//       "raw": "https://images.unsplash.com/photo-1551973932-8131a944f98e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//         "regular": "https://images.unsplash.com/photo-1551973932-8131a944f98e?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//           "small": "https://images.unsplash.com/photo-1551973932-8131a944f98e?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//             "thumb": "https://images.unsplash.com/photo-1551973932-8131a944f98e?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//     },
//   "user": Object {
//     "accepted_tos": true,
//       "bio": "My goal is to dream big, be awesome, change lives, and maybe get some cool shots I can share with you along the way.",
//         "first_name": "Clayton",
//           "id": "XWgtCn3n3KU",
//             "instagram_username": "clayton_cardinalli",
//               "last_name": "Cardinalli",
//                 "links": Object {
//       "followers": "https://api.unsplash.com/users/clayton_cardinalli/followers",
//         "following": "https://api.unsplash.com/users/clayton_cardinalli/following",
//           "html": "https://unsplash.com/@clayton_cardinalli",
//             "likes": "https://api.unsplash.com/users/clayton_cardinalli/likes",
//               "photos": "https://api.unsplash.com/users/clayton_cardinalli/photos",
//                 "portfolio": "https://api.unsplash.com/users/clayton_cardinalli/portfolio",
//                   "self": "https://api.unsplash.com/users/clayton_cardinalli",
//       },
//     "location": "Cape Town",
//       "name": "Clayton Cardinalli",
//         "portfolio_url": "https://www.havedronecanfly.com/",
//           "profile_image": Object {
//       "large": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
//         "medium": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64",
//           "small": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32",
//       },
//     "total_collections": 3,
//       "total_likes": 50,
//         "total_photos": 51,
//           "twitter_username": "clayton_card",
//             "updated_at": "2019-03-06T09:10:12-05:00",
//               "username": "clayton_cardinalli",
//     },
//   "width": 3000,
//   },
// Object {
//   "alt_description": null,
//     "categories": Array[],
//       "color": "#D3DBE1",
//         "created_at": "2019-03-07T11:23:24-05:00",
//           "current_user_collections": Array[],
//             "description": null,
//               "height": 6000,
//                 "id": "eh2Jy0S5RgE",
//                   "liked_by_user": false,
//                     "likes": 11,
//                       "links": Object {
//     "download": "https://unsplash.com/photos/eh2Jy0S5RgE/download",
//       "download_location": "https://api.unsplash.com/photos/eh2Jy0S5RgE/download",
//         "html": "https://unsplash.com/photos/eh2Jy0S5RgE",
//           "self": "https://api.unsplash.com/photos/eh2Jy0S5RgE",
//     },
//   "sponsored": false,
//     "sponsored_by": null,
//       "sponsored_impressions_id": null,
//         "updated_at": "2019-03-08T11:14:40-05:00",
//           "urls": Object {
//     "full": "https://images.unsplash.com/photo-1551973932-86019142d146?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//       "raw": "https://images.unsplash.com/photo-1551973932-86019142d146?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//         "regular": "https://images.unsplash.com/photo-1551973932-86019142d146?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//           "small": "https://images.unsplash.com/photo-1551973932-86019142d146?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//             "thumb": "https://images.unsplash.com/photo-1551973932-86019142d146?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//     },
//   "user": Object {
//     "accepted_tos": true,
//       "bio": "My goal is to dream big, be awesome, change lives, and maybe get some cool shots I can share with you along the way.",
//         "first_name": "Clayton",
//           "id": "XWgtCn3n3KU",
//             "instagram_username": "clayton_cardinalli",
//               "last_name": "Cardinalli",
//                 "links": Object {
//       "followers": "https://api.unsplash.com/users/clayton_cardinalli/followers",
//         "following": "https://api.unsplash.com/users/clayton_cardinalli/following",
//           "html": "https://unsplash.com/@clayton_cardinalli",
//             "likes": "https://api.unsplash.com/users/clayton_cardinalli/likes",
//               "photos": "https://api.unsplash.com/users/clayton_cardinalli/photos",
//                 "portfolio": "https://api.unsplash.com/users/clayton_cardinalli/portfolio",
//                   "self": "https://api.unsplash.com/users/clayton_cardinalli",
//       },
//     "location": "Cape Town",
//       "name": "Clayton Cardinalli",
//         "portfolio_url": "https://www.havedronecanfly.com/",
//           "profile_image": Object {
//       "large": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
//         "medium": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64",
//           "small": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32",
//       },
//     "total_collections": 3,
//       "total_likes": 50,
//         "total_photos": 51,
//           "twitter_username": "clayton_card",
//             "updated_at": "2019-03-06T09:10:12-05:00",
//               "username": "clayton_cardinalli",
//     },
//   "width": 4000,
//   },
// Object {
//   "alt_description": null,
//     "categories": Array[],
//       "color": "#101718",
//         "created_at": "2019-03-07T11:23:24-05:00",
//           "current_user_collections": Array[],
//             "description": null,
//               "height": 3000,
//                 "id": "Eha6XnwAEiE",
//                   "liked_by_user": false,
//                     "likes": 15,
//                       "links": Object {
//     "download": "https://unsplash.com/photos/Eha6XnwAEiE/download",
//       "download_location": "https://api.unsplash.com/photos/Eha6XnwAEiE/download",
//         "html": "https://unsplash.com/photos/Eha6XnwAEiE",
//           "self": "https://api.unsplash.com/photos/Eha6XnwAEiE",
//     },
//   "sponsored": false,
//     "sponsored_by": null,
//       "sponsored_impressions_id": null,
//         "updated_at": "2019-03-08T11:14:39-05:00",
//           "urls": Object {
//     "full": "https://images.unsplash.com/photo-1551973931-83ed7323ea15?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//       "raw": "https://images.unsplash.com/photo-1551973931-83ed7323ea15?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//         "regular": "https://images.unsplash.com/photo-1551973931-83ed7323ea15?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//           "small": "https://images.unsplash.com/photo-1551973931-83ed7323ea15?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//             "thumb": "https://images.unsplash.com/photo-1551973931-83ed7323ea15?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//     },
//   "user": Object {
//     "accepted_tos": true,
//       "bio": "My goal is to dream big, be awesome, change lives, and maybe get some cool shots I can share with you along the way.",
//         "first_name": "Clayton",
//           "id": "XWgtCn3n3KU",
//             "instagram_username": "clayton_cardinalli",
//               "last_name": "Cardinalli",
//                 "links": Object {
//       "followers": "https://api.unsplash.com/users/clayton_cardinalli/followers",
//         "following": "https://api.unsplash.com/users/clayton_cardinalli/following",
//           "html": "https://unsplash.com/@clayton_cardinalli",
//             "likes": "https://api.unsplash.com/users/clayton_cardinalli/likes",
//               "photos": "https://api.unsplash.com/users/clayton_cardinalli/photos",
//                 "portfolio": "https://api.unsplash.com/users/clayton_cardinalli/portfolio",
//                   "self": "https://api.unsplash.com/users/clayton_cardinalli",
//       },
//     "location": "Cape Town",
//       "name": "Clayton Cardinalli",
//         "portfolio_url": "https://www.havedronecanfly.com/",
//           "profile_image": Object {
//       "large": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
//         "medium": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64",
//           "small": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32",
//       },
//     "total_collections": 3,
//       "total_likes": 50,
//         "total_photos": 51,
//           "twitter_username": "clayton_card",
//             "updated_at": "2019-03-06T09:10:12-05:00",
//               "username": "clayton_cardinalli",
//     },
//   "width": 4000,
//   },
// Object {
//   "alt_description": null,
//     "categories": Array[],
//       "color": "#0D0F10",
//         "created_at": "2019-03-07T11:23:24-05:00",
//           "current_user_collections": Array[],
//             "description": null,
//               "height": 6000,
//                 "id": "0Yi2i5JlMpU",
//                   "liked_by_user": false,
//                     "likes": 0,
//                       "links": Object {
//     "download": "https://unsplash.com/photos/0Yi2i5JlMpU/download",
//       "download_location": "https://api.unsplash.com/photos/0Yi2i5JlMpU/download",
//         "html": "https://unsplash.com/photos/0Yi2i5JlMpU",
//           "self": "https://api.unsplash.com/photos/0Yi2i5JlMpU",
//     },
//   "sponsored": false,
//     "sponsored_by": null,
//       "sponsored_impressions_id": null,
//         "updated_at": "2019-03-08T10:32:56-05:00",
//           "urls": Object {
//     "full": "https://images.unsplash.com/photo-1551973931-a4f23df8ad6a?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//       "raw": "https://images.unsplash.com/photo-1551973931-a4f23df8ad6a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//         "regular": "https://images.unsplash.com/photo-1551973931-a4f23df8ad6a?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//           "small": "https://images.unsplash.com/photo-1551973931-a4f23df8ad6a?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//             "thumb": "https://images.unsplash.com/photo-1551973931-a4f23df8ad6a?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//     },
//   "user": Object {
//     "accepted_tos": true,
//       "bio": "My goal is to dream big, be awesome, change lives, and maybe get some cool shots I can share with you along the way.",
//         "first_name": "Clayton",
//           "id": "XWgtCn3n3KU",
//             "instagram_username": "clayton_cardinalli",
//               "last_name": "Cardinalli",
//                 "links": Object {
//       "followers": "https://api.unsplash.com/users/clayton_cardinalli/followers",
//         "following": "https://api.unsplash.com/users/clayton_cardinalli/following",
//           "html": "https://unsplash.com/@clayton_cardinalli",
//             "likes": "https://api.unsplash.com/users/clayton_cardinalli/likes",
//               "photos": "https://api.unsplash.com/users/clayton_cardinalli/photos",
//                 "portfolio": "https://api.unsplash.com/users/clayton_cardinalli/portfolio",
//                   "self": "https://api.unsplash.com/users/clayton_cardinalli",
//       },
//     "location": "Cape Town",
//       "name": "Clayton Cardinalli",
//         "portfolio_url": "https://www.havedronecanfly.com/",
//           "profile_image": Object {
//       "large": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
//         "medium": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64",
//           "small": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32",
//       },
//     "total_collections": 3,
//       "total_likes": 50,
//         "total_photos": 51,
//           "twitter_username": "clayton_card",
//             "updated_at": "2019-03-06T09:10:12-05:00",
//               "username": "clayton_cardinalli",
//     },
//   "width": 4000,
//   },
// Object {
//   "categories": Array[],
//     "color": "#E7DBC7",
//       "created_at": "2019-03-07T11:23:24-05:00",
//         "current_user_collections": Array[],
//           "description": null,
//             "height": 5767,
//               "id": "cOdgF3ua7o8",
//                 "liked_by_user": false,
//                   "likes": 0,
//                     "links": Object {
//     "download": "https://unsplash.com/photos/cOdgF3ua7o8/download",
//       "download_location": "https://api.unsplash.com/photos/cOdgF3ua7o8/download",
//         "html": "https://unsplash.com/photos/cOdgF3ua7o8",
//           "self": "https://api.unsplash.com/photos/cOdgF3ua7o8",
//     },
//   "sponsored": false,
//     "sponsored_by": null,
//       "sponsored_impressions_id": null,
//         "updated_at": "2019-03-07T11:23:25-05:00",
//           "urls": Object {
//     "full": "https://images.unsplash.com/photo-1551973932-b34644121958?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//       "raw": "https://images.unsplash.com/photo-1551973932-b34644121958?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//         "regular": "https://images.unsplash.com/photo-1551973932-b34644121958?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//           "small": "https://images.unsplash.com/photo-1551973932-b34644121958?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//             "thumb": "https://images.unsplash.com/photo-1551973932-b34644121958?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//     },
//   "user": Object {
//     "accepted_tos": true,
//       "bio": "My goal is to dream big, be awesome, change lives, and maybe get some cool shots I can share with you along the way.",
//         "first_name": "Clayton",
//           "id": "XWgtCn3n3KU",
//             "instagram_username": "clayton_cardinalli",
//               "last_name": "Cardinalli",
//                 "links": Object {
//       "followers": "https://api.unsplash.com/users/clayton_cardinalli/followers",
//         "following": "https://api.unsplash.com/users/clayton_cardinalli/following",
//           "html": "https://unsplash.com/@clayton_cardinalli",
//             "likes": "https://api.unsplash.com/users/clayton_cardinalli/likes",
//               "photos": "https://api.unsplash.com/users/clayton_cardinalli/photos",
//                 "portfolio": "https://api.unsplash.com/users/clayton_cardinalli/portfolio",
//                   "self": "https://api.unsplash.com/users/clayton_cardinalli",
//       },
//     "location": "Cape Town",
//       "name": "Clayton Cardinalli",
//         "portfolio_url": "https://www.havedronecanfly.com/",
//           "profile_image": Object {
//       "large": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
//         "medium": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64",
//           "small": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32",
//       },
//     "total_collections": 3,
//       "total_likes": 50,
//         "total_photos": 51,
//           "twitter_username": "clayton_card",
//             "updated_at": "2019-03-06T09:10:12-05:00",
//               "username": "clayton_cardinalli",
//     },
//   "width": 3845,
//   },
// Object {
//   "categories": Array[],
//     "color": "#010A1D",
//       "created_at": "2019-03-04T01:28:12-05:00",
//         "current_user_collections": Array[],
//           "description": "boat at sea during daytime",
//             "height": 2704,
//               "id": "yg5t96-e27A",
//                 "liked_by_user": false,
//                   "likes": 0,
//                     "links": Object {
//     "download": "https://unsplash.com/photos/yg5t96-e27A/download",
//       "download_location": "https://api.unsplash.com/photos/yg5t96-e27A/download",
//         "html": "https://unsplash.com/photos/yg5t96-e27A",
//           "self": "https://api.unsplash.com/photos/yg5t96-e27A",
//     },
//   "sponsored": false,
//     "sponsored_by": null,
//       "sponsored_impressions_id": null,
//         "updated_at": "2019-03-06T14:01:20-05:00",
//           "urls": Object {
//     "full": "https://images.unsplash.com/photo-1551679516-e1272911f1c6?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//       "raw": "https://images.unsplash.com/photo-1551679516-e1272911f1c6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//         "regular": "https://images.unsplash.com/photo-1551679516-e1272911f1c6?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//           "small": "https://images.unsplash.com/photo-1551679516-e1272911f1c6?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//             "thumb": "https://images.unsplash.com/photo-1551679516-e1272911f1c6?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//     },
//   "user": Object {
//     "accepted_tos": true,
//       "bio": "My goal is to dream big, be awesome, change lives, and maybe get some cool shots I can share with you along the way.",
//         "first_name": "Clayton",
//           "id": "XWgtCn3n3KU",
//             "instagram_username": "clayton_cardinalli",
//               "last_name": "Cardinalli",
//                 "links": Object {
//       "followers": "https://api.unsplash.com/users/clayton_cardinalli/followers",
//         "following": "https://api.unsplash.com/users/clayton_cardinalli/following",
//           "html": "https://unsplash.com/@clayton_cardinalli",
//             "likes": "https://api.unsplash.com/users/clayton_cardinalli/likes",
//               "photos": "https://api.unsplash.com/users/clayton_cardinalli/photos",
//                 "portfolio": "https://api.unsplash.com/users/clayton_cardinalli/portfolio",
//                   "self": "https://api.unsplash.com/users/clayton_cardinalli",
//       },
//     "location": "Cape Town",
//       "name": "Clayton Cardinalli",
//         "portfolio_url": "https://www.havedronecanfly.com/",
//           "profile_image": Object {
//       "large": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
//         "medium": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64",
//           "small": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32",
//       },
//     "total_collections": 3,
//       "total_likes": 50,
//         "total_photos": 51,
//           "twitter_username": "clayton_card",
//             "updated_at": "2019-03-06T09:10:12-05:00",
//               "username": "clayton_cardinalli",
//     },
//   "width": 3606,
//   },
// Object {
//   "categories": Array[],
//     "color": "#018080",
//       "created_at": "2019-03-04T01:28:12-05:00",
//         "current_user_collections": Array[],
//           "description": "shark under water",
//             "height": 4000,
//               "id": "mbojghGv6yQ",
//                 "liked_by_user": false,
//                   "likes": 0,
//                     "links": Object {
//     "download": "https://unsplash.com/photos/mbojghGv6yQ/download",
//       "download_location": "https://api.unsplash.com/photos/mbojghGv6yQ/download",
//         "html": "https://unsplash.com/photos/mbojghGv6yQ",
//           "self": "https://api.unsplash.com/photos/mbojghGv6yQ",
//     },
//   "sponsored": false,
//     "sponsored_by": null,
//       "sponsored_impressions_id": null,
//         "updated_at": "2019-03-06T14:01:20-05:00",
//           "urls": Object {
//     "full": "https://images.unsplash.com/photo-1551679516-63369f484009?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//       "raw": "https://images.unsplash.com/photo-1551679516-63369f484009?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//         "regular": "https://images.unsplash.com/photo-1551679516-63369f484009?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//           "small": "https://images.unsplash.com/photo-1551679516-63369f484009?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//             "thumb": "https://images.unsplash.com/photo-1551679516-63369f484009?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjMyNDU2fQ",
//     },
//   "user": Object {
//     "accepted_tos": true,
//       "bio": "My goal is to dream big, be awesome, change lives, and maybe get some cool shots I can share with you along the way.",
//         "first_name": "Clayton",
//           "id": "XWgtCn3n3KU",
//             "instagram_username": "clayton_cardinalli",
//               "last_name": "Cardinalli",
//                 "links": Object {
//       "followers": "https://api.unsplash.com/users/clayton_cardinalli/followers",
//         "following": "https://api.unsplash.com/users/clayton_cardinalli/following",
//           "html": "https://unsplash.com/@clayton_cardinalli",
//             "likes": "https://api.unsplash.com/users/clayton_cardinalli/likes",
//               "photos": "https://api.unsplash.com/users/clayton_cardinalli/photos",
//                 "portfolio": "https://api.unsplash.com/users/clayton_cardinalli/portfolio",
//                   "self": "https://api.unsplash.com/users/clayton_cardinalli",
//       },
//     "location": "Cape Town",
//       "name": "Clayton Cardinalli",
//         "portfolio_url": "https://www.havedronecanfly.com/",
//           "profile_image": Object {
//       "large": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128",
//         "medium": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64",
//           "small": "https://images.unsplash.com/profile-1541066427084-81130f25b5ff?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32",
//       },
//     "total_collections": 3,
//       "total_likes": 50,
//         "total_photos": 51,
//           "twitter_username": "clayton_card",
//             "updated_at": "2019-03-06T09:10:12-05:00",
//               "username": "clayton_cardinalli",
//     },
//   "width": 6000,
//   },
// ]
